public class SRV_UY_AccountWrapper {
    @AuraEnabled@InvocableVariable public String documentType;
    @AuraEnabled@InvocableVariable public String documentNumber;
    @AuraEnabled@InvocableVariable public String firstName;
    @AuraEnabled@InvocableVariable public String secondName;
    @AuraEnabled@InvocableVariable public String lastName;
    @AuraEnabled@InvocableVariable public String secondLastName;
    @AuraEnabled@InvocableVariable public String maritalStatus;
    @AuraEnabled@InvocableVariable public String personBirthdate;
    @AuraEnabled@InvocableVariable public String nationality;
    @AuraEnabled@InvocableVariable public String occupation;
    @AuraEnabled@InvocableVariable public String phone;
    @AuraEnabled@InvocableVariable public String personMobilePhone;
    @AuraEnabled@InvocableVariable public String email;
}